### ISSUE TITLE
关于直接拉取代码到本地运行example目录中的demo报错问题

### ISSUE THREAD

**Issue by treasureTa** [pysunday/sdenv#2]
报错问题： TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received type boolean (false)

// 解决
前往utils目录下找到paths.js文件。将文件中的  / 修改为 `\\` 就行

**Comment by treasureTa** [comment]
修改后的paths.js代码

const path = require('path');
const fs = require('fs');

const appDirectory = (() => {
  // 返回项目根目录
  const plist = fs.realpathSync(__dirname).split('\\');
  while (!fs.existsSync(path.resolve(plist.join('\\'), 'package.json'))) {
    plist.pop();
    if (plist.length === 0) return false;
  }
  return plist.join('/');
})();

const resolveApp = (...relativePath) => path.resolve(appDirectory, ...relativePath);
module.exports = {
  basePath: resolveApp(''),
  homePath: __dirname,
  modulePath: resolveApp('node_modules'),
  binPath: resolveApp('node_modules/.bin/'),
  package: resolveApp('package.json'),
  resolve: resolveApp,
  handlerPath: resolveApp('handler'),
  configPath: resolveApp('config'),
  configResolve: (...p) => resolveApp('config', ...p),
};

**Comment by pysunday** [comment]
bug已修复，感谢反馈！
